version: "3"
services:

  #certbot_autorenew:
  #  # This is the certbot container. It only needs the letsencrypt directory
  #  # for renewing the certificates automatically, it does not need open ports.
  #  # For creating a new certificate (also the case if the certificate expired)
  #  # you need to run the container interactively
  #  build: certbot_autorenew/
  #  volumes:
  #    - "/docker/letsencrypt:/etc/letsencrypt:rw"
  #  restart: always

  nginx_frontend:
    # Using a slightly modified nginx image to automatically detect the
    # certificate's FQDN from letsencrypt, and substitute variables using
    # envsubst. We need to expose ports 80 and 443
    build: nginx_frontend/
    environment:
      NGINX_EXTERNAL_HTTPS_PORT: 6443
      NGINX_EXTERNAL_HTTP_PORT: 6080
    ports:
      - "6080:80"
      - "6443:443"
    volumes:
      - "./persistent/www:/var/www:ro"
      - "./persistent/letsencrypt:/etc/letsencrypt:ro"
      - "./persistent/cache:/cache:rw"
      - "./nginx_frontend/my.conf.template:/etc/nginx/conf.d/my.conf.template:ro"
    restart: always
