version: "3"
services:

  frontend:
    build: frontend/
    environment:
      # make sure the numbers here match the ports in the `ports:` section
      FRONTEND_EXTERNAL_HTTPS_PORT: 443
      FRONTEND_EXTERNAL_HTTP_PORT: 80
    ports:
      # external:internal
      - "80:80"
      - "443:443"
    volumes:
      # paths beginning with ./ are relative to the dir containing this docker-compose.yml file
      - "./data/certbot/conf:/etc/letsencrypt:ro"
      - "./data/certbot/www:/var/www/certbot:ro"
      - "./frontend/frontend.conf.template:/frontend.conf.template:ro"  # configuration file
    depends_on:
      - certbot
      - revproxy
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      # paths beginning with ./ are relative to the dir containing this docker-compose.yml file
      - "./data/certbot/conf:/etc/letsencrypt:rw"
      - "./data/certbot/www:/var/www/certbot:rw"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

  revproxy:
    build: revproxy/
    environment:
      REVPROXY_REDIRECT_INVALID_TO: "https://start.duckduckgo.com"
      REVPROXY_BACKEND_PREFIX: "http://ali-ci.cern.ch"
      REVPROXY_LOCAL_ROOT: "/cache"
      REVPROXY_CACHE_FILE_DURATION: 2592000  # one month
    command: /revproxy/revproxy.py
    volumes:
      # paths beginning with ./ are relative to the dir containing this docker-compose.yml file
      - "./data/revproxy_cache:/cache:rw"  # cache
    restart: always
