version: "3"
services:

  frontend:
    build: frontend/
    environment:
      # make sure the numbers here match the ports in the `ports:` section
      FRONTEND_EXTERNAL_HTTPS_PORT: 6443
      FRONTEND_EXTERNAL_HTTP_PORT: 6080
    ports:
      # external:internal
      - "6080:80"
      - "6443:443"
    volumes:
      # paths beginning with ./ are relative to the dir containing this docker-compose.yml file
      - "./persistent/letsencrypt:/letsencrypt:ro"                      # certificates
      - "./frontend/frontend.conf.template:/frontend.conf.template:ro"  # configuration file
    depends_on:
      - revproxy
    restart: always

  revproxy:
    build: revproxy/
    environment:
      REVPROXY_REDIRECT_INVALID_TO: "https://start.duckduckgo.com"
      REVPROXY_BACKEND_PREFIX: "http://ali-ci.cern.ch"
      REVPROXY_LOCAL_ROOT: "/cache"
      REVPROXY_CACHE_FILE_DURATION: 2592000  # one month
    command: /revproxy/revproxy.py
    volumes:
      # paths beginning with ./ are relative to the dir containing this docker-compose.yml file
      - "./persistent/revproxy_cache:/cache:rw"  # cache
    restart: always
